//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "5c02d01d285c3cd0")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("Home")]
	public partial class Home : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// AboutCarousel1: AboutCarousel1.
		///</summary>
		[ImplementPropertyType("aboutCarousel1")]
		public object AboutCarousel1
		{
			get { return this.GetPropertyValue("aboutCarousel1"); }
		}

		///<summary>
		/// AboutContent: AboutContent.
		///</summary>
		[ImplementPropertyType("aboutContent")]
		public string AboutContent
		{
			get { return this.GetPropertyValue<string>("aboutContent"); }
		}

		///<summary>
		/// AboutPanels: AboutPanels.
		///</summary>
		[ImplementPropertyType("aboutPanels")]
		public object AboutPanels
		{
			get { return this.GetPropertyValue("aboutPanels"); }
		}

		///<summary>
		/// AboutSubTitle: AboutSubTitle.
		///</summary>
		[ImplementPropertyType("aboutSubTitle")]
		public string AboutSubTitle
		{
			get { return this.GetPropertyValue<string>("aboutSubTitle"); }
		}

		///<summary>
		/// AboutTitle: AboutTitle.
		///</summary>
		[ImplementPropertyType("aboutTitle")]
		public string AboutTitle
		{
			get { return this.GetPropertyValue<string>("aboutTitle"); }
		}

		///<summary>
		/// BackgroundImage: BackgroundImage.
		///</summary>
		[ImplementPropertyType("backgroundImage")]
		public string BackgroundImage
		{
			get { return this.GetPropertyValue<string>("backgroundImage"); }
		}

		///<summary>
		/// Contact Blurb: Contact Blurb.
		///</summary>
		[ImplementPropertyType("contactBlurb")]
		public string ContactBlurb
		{
			get { return this.GetPropertyValue<string>("contactBlurb"); }
		}

		///<summary>
		/// CTAButtonText: CTAButtonText.
		///</summary>
		[ImplementPropertyType("cTAButtonText")]
		public string CTabuttonText
		{
			get { return this.GetPropertyValue<string>("cTAButtonText"); }
		}

		///<summary>
		/// CTAText: CTAText.
		///</summary>
		[ImplementPropertyType("cTAText")]
		public string CTatext
		{
			get { return this.GetPropertyValue<string>("cTAText"); }
		}

		///<summary>
		/// CTATitle: CTATitle.
		///</summary>
		[ImplementPropertyType("cTATitle")]
		public string CTatitle
		{
			get { return this.GetPropertyValue<string>("cTATitle"); }
		}

		///<summary>
		/// FaceBook: FaceBook.
		///</summary>
		[ImplementPropertyType("faceBook")]
		public string FaceBook
		{
			get { return this.GetPropertyValue<string>("faceBook"); }
		}

		///<summary>
		/// GalleryTitle: GalleryTitle.
		///</summary>
		[ImplementPropertyType("galleryTitle")]
		public string GalleryTitle
		{
			get { return this.GetPropertyValue<string>("galleryTitle"); }
		}

		///<summary>
		/// GooglePlus: GooglePlus.
		///</summary>
		[ImplementPropertyType("googlePlus")]
		public string GooglePlus
		{
			get { return this.GetPropertyValue<string>("googlePlus"); }
		}

		///<summary>
		/// H1Tag: H1Tag.
		///</summary>
		[ImplementPropertyType("h1Tag")]
		public string H1Tag
		{
			get { return this.GetPropertyValue<string>("h1Tag"); }
		}

		///<summary>
		/// Images: Images.
		///</summary>
		[ImplementPropertyType("images")]
		public string Images
		{
			get { return this.GetPropertyValue<string>("images"); }
		}

		///<summary>
		/// Address: Address.
		///</summary>
		[ImplementPropertyType("infoAddress")]
		public string InfoAddress
		{
			get { return this.GetPropertyValue<string>("infoAddress"); }
		}

		///<summary>
		/// Email: Email.
		///</summary>
		[ImplementPropertyType("infoEmail")]
		public string InfoEmail
		{
			get { return this.GetPropertyValue<string>("infoEmail"); }
		}

		///<summary>
		/// Phone: Phone.
		///</summary>
		[ImplementPropertyType("infoPhone")]
		public string InfoPhone
		{
			get { return this.GetPropertyValue<string>("infoPhone"); }
		}

		///<summary>
		/// Instagram: Instagram.
		///</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return this.GetPropertyValue<string>("instagram"); }
		}

		///<summary>
		/// LinkedIn: LinkedIn.
		///</summary>
		[ImplementPropertyType("linkedIn")]
		public string LinkedIn
		{
			get { return this.GetPropertyValue<string>("linkedIn"); }
		}

		///<summary>
		/// ListTitle: ListTitle.
		///</summary>
		[ImplementPropertyType("listTitle")]
		public string ListTitle
		{
			get { return this.GetPropertyValue<string>("listTitle"); }
		}

		///<summary>
		/// MetaDescription: MetaDescription.
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return this.GetPropertyValue<string>("metaDescription"); }
		}

		///<summary>
		/// MetaKeywords: MetaKeywords.
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return this.GetPropertyValue<string>("metaKeywords"); }
		}

		///<summary>
		/// MetaTitle: MetaTitle.
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return this.GetPropertyValue<string>("metaTitle"); }
		}

		///<summary>
		/// PriceList: PriceList.
		///</summary>
		[ImplementPropertyType("priceList")]
		public object PriceList
		{
			get { return this.GetPropertyValue("priceList"); }
		}

		///<summary>
		/// PriceList2: PriceList2.
		///</summary>
		[ImplementPropertyType("priceList2")]
		public object PriceList2
		{
			get { return this.GetPropertyValue("priceList2"); }
		}

		///<summary>
		/// PricesTitle: PricesTitle.
		///</summary>
		[ImplementPropertyType("pricesTitle")]
		public string PricesTitle
		{
			get { return this.GetPropertyValue<string>("pricesTitle"); }
		}

		///<summary>
		/// ServicePanels: ServicePanels.
		///</summary>
		[ImplementPropertyType("servicePanels")]
		public object ServicePanels
		{
			get { return this.GetPropertyValue("servicePanels"); }
		}

		///<summary>
		/// ServicesContent: ServicesContent.
		///</summary>
		[ImplementPropertyType("servicesContent")]
		public string ServicesContent
		{
			get { return this.GetPropertyValue<string>("servicesContent"); }
		}

		///<summary>
		/// ServicesSubTitle: ServicesSubTitle.
		///</summary>
		[ImplementPropertyType("servicesSubTitle")]
		public string ServicesSubTitle
		{
			get { return this.GetPropertyValue<string>("servicesSubTitle"); }
		}

		///<summary>
		/// ServicesTitle: ServicesTitle.
		///</summary>
		[ImplementPropertyType("servicesTitle")]
		public string ServicesTitle
		{
			get { return this.GetPropertyValue<string>("servicesTitle"); }
		}

		///<summary>
		/// Slide 1: Slide 1.
		///</summary>
		[ImplementPropertyType("slide1")]
		public string Slide1
		{
			get { return this.GetPropertyValue<string>("slide1"); }
		}

		///<summary>
		/// Twitter: Twitter.
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}
	}

	/// <summary>HoldingPage</summary>
	[PublishedContentModel("HoldingPage")]
	public partial class HoldingPage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "HoldingPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HoldingPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HoldingPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BackgroundImage: BackgroundImage.
		///</summary>
		[ImplementPropertyType("backgroundImage")]
		public string BackgroundImage
		{
			get { return this.GetPropertyValue<string>("backgroundImage"); }
		}

		///<summary>
		/// Description: Description.
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// Facebook: Facebook.
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		///<summary>
		/// LinkedIn: LinkedIn.
		///</summary>
		[ImplementPropertyType("linkedIn")]
		public string LinkedIn
		{
			get { return this.GetPropertyValue<string>("linkedIn"); }
		}

		///<summary>
		/// Logo: Logo.
		///</summary>
		[ImplementPropertyType("logo")]
		public string Logo
		{
			get { return this.GetPropertyValue<string>("logo"); }
		}

		///<summary>
		/// Title: Title.
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Twitter: Twitter.
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
